export const APP_NAME = "GrowSmart";
export const APP_AUTHORS = "Mithun & Manoj";

export const KARNATAKA_DISTRICTS: string[] = [
  "Bagalkot", "Ballari (Bellary)", "Belagavi (Belgaum)", "Bengaluru Rural", 
  "Bengaluru Urban", "Bidar", "Chamarajanagar", "Chikballapur", 
  "Chikkamagaluru", "Chitradurga", "Dakshina Kannada", "Davanagere", 
  "Dharwad", "Gadag", "Hassan", "Haveri", "Kalaburagi (Gulbarga)", 
  "Kodagu", "Kolar", "Koppal", "Mandya", "Mysuru (Mysore)", 
  "Raichur", "Ramanagara", "Shivamogga (Shimoga)", "Tumakuru (Tumkur)", 
  "Udupi", "Uttara Kannada", "Vijayapura (Bijapur)", "Yadgir"
];

// Kannada translations for districts
export const DISTRICT_NAMES_KANNADA: Record<string, string> = {
  "Bagalkot": "ಬಾಗಲಕೋಟೆ",
  "Ballari (Bellary)": "ಬಳ್ಳಾರಿ",
  "Belagavi (Belgaum)": "ಬೆಳಗಾವಿ",
  "Bengaluru Rural": "ಬೆಂಗಳೂರು ಗ್ರಾಮಾಂತರ",
  "Bengaluru Urban": "ಬೆಂಗಳೂರು ನಗರ",
  "Bidar": "ಬೀದರ್",
  "Chamarajanagar": "ಚಾಮರಾಜನಗರ",
  "Chikballapur": "ಚಿಕ್ಕಬಳ್ಳಾಪುರ",
  "Chikkamagaluru": "ಚಿಕ್ಕಮಗಳೂರು",
  "Chitradurga": "ಚಿತ್ರದುರ್ಗ",
  "Dakshina Kannada": "ದಕ್ಷಿಣ ಕನ್ನಡ",
  "Davanagere": "ದಾವಣಗೆರೆ",
  "Dharwad": "ಧಾರವಾಡ",
  "Gadag": "ಗದಗ",
  "Hassan": "ಹಾಸನ",
  "Haveri": "ಹಾವೇರಿ",
  "Kalaburagi (Gulbarga)": "ಕಲಬುರಗಿ",
  "Kodagu": "ಕೊಡಗು",
  "Kolar": "ಕೋಲಾರ",
  "Koppal": "ಕೊಪ್ಪಳ",
  "Mandya": "ಮಂಡ್ಯ",
  "Mysuru (Mysore)": "ಮೈಸೂರು",
  "Raichur": "ರಾಯಚೂರು",
  "Ramanagara": "ರಾಮನಗರ",
  "Shivamogga (Shimoga)": "ಶಿವಮೊಗ್ಗ",
  "Tumakuru (Tumkur)": "ತುಮಕೂರು",
  "Udupi": "ಉಡುಪಿ",
  "Uttara Kannada": "ಉತ್ತರ ಕನ್ನಡ",
  "Vijayapura (Bijapur)": "ವಿಜಯಪುರ",
  "Yadgir": "ಯಾದಗಿರಿ"
};

export interface PlantCategory {
  name: string;
  emoji: string;
  searchKeywords?: string; // For more detailed category searches if needed later
}

export const PLANT_CATEGORIES: PlantCategory[] = [
  // Fruits
  { name: "Apple", emoji: "🍎" },
  { name: "Banana", emoji: "🍌" },
  { name: "Grapes", emoji: "🍇" },
  { name: "Strawberry", emoji: "🍓" },
  { name: "Orange", emoji: "🍊" },
  { name: "Lemon", emoji: "🍋" },
  { name: "Mango", emoji: "🥭" },
  { name: "Pineapple", emoji: "🍍" },
  { name: "Watermelon", emoji: "🍉" },
  { name: "Pomegranate", emoji: "🔴" }, // Needs better emoji
  { name: "Cherry", emoji: "🍒" },
  { name: "Peach", emoji: "🍑" },
  { name: "Pear", emoji: "🍐" },
  { name: "Kiwi", emoji: "🥝" },
  { name: "Avocado", emoji: "🥑" },
  { name: "Coconut", emoji: "🥥" },
  { name: "Fig", emoji: "🪴" }, // Generic plant for fig
  { name: "Plum", emoji: "🍑" }, // Using peach as similar
  { name: "Guava", emoji: "🍈" }, // Using melon as generic tropical
  { name: "Papaya", emoji: "🥭" }, // Using mango as generic tropical
  // Vegetables
  { name: "Tomato", emoji: "🍅" },
  { name: "Potato", emoji: "🥔" },
  { name: "Carrot", emoji: "🥕" },
  { name: "Broccoli", emoji: "🥦" },
  { name: "Spinach", emoji: "🥬" },
  { name: "Onion", emoji: "🧅" },
  { name: "Garlic", emoji: "🧄" },
  { name: "Eggplant", emoji: "🍆" },
  { name: "Cucumber", emoji: "🥒" },
  { name: "Bell Pepper", emoji: "🌶️" },
  { name: "Lettuce", emoji: "🥬" },
  { name: "Pumpkin", emoji: "🎃" },
  { name: "Zucchini", emoji: "🥒" }, // Using cucumber
  { name: "Cauliflower", emoji: "🥦" }, // Using broccoli
  { name: "Radish", emoji: "🥕" }, // Using carrot for root veg
  { name: "Sweet Potato", emoji: "🍠" },
  { name: "Asparagus", emoji: "🥬" }, // Leafy green for asparagus
  { name: "Celery", emoji: "🥬" }, // Using lettuce/spinach
  { name: "Mushroom", emoji: "🍄" }, // Fungi
  { name: "Corn (Maize)", emoji: "🌽" },
  // Ornamentals
  { name: "Rose", emoji: "🌹" },
  { name: "Sunflower", emoji: "🌻" },
  { name: "Tulip", emoji: "🌷" },
  { name: "Lily", emoji: "🌸" },
  { name: "Orchid", emoji: "🌺" },
  { name: "Fern", emoji: "🌿" },
  { name: "Bonsai", emoji: "🌳" },
  { name: "Cactus", emoji: "🌵" },
  { name: "Lavender", emoji: "💐" },
  { name: "Marigold", emoji: "🌼" },
  { name: "Hibiscus", emoji: "🌺" },
  { name: "Daisy", emoji: "🌼" }, // Using marigold/sunflower
  { name: "Peony", emoji: "🌸" }, // Using generic flower
  { name: "Succulent", emoji: "🪴" }, // Generic potted plant
  { name: "Ivy", emoji: "🌿" },
  { name: "Fiddle Leaf Fig", emoji: "🌳" },
  { name: "Monstera", emoji: "🍃" },
  { name: "Snake Plant", emoji: "🪴" },
  { name: "Spider Plant", emoji: "🪴" },
  // Herbs
  { name: "Basil", emoji: "🌿" },
  { name: "Mint", emoji: "🍃" },
  { name: "Rosemary", emoji: "🌿" },
  { name: "Thyme", emoji: "🌿" },
  { name: "Cilantro (Coriander)", emoji: "🌿" },
  { name: "Parsley", emoji: "🌿" },
  { name: "Dill", emoji: "🌿" },
  { name: "Oregano", emoji: "🌿" },
  { name: "Sage", emoji: "🌿" },
  { name: "Chamomile", emoji: "🌼" }, // Flower used for tea
  // Grains & Cereals
  { name: "Wheat", emoji: "🌾" },
  { name: "Rice", emoji: "🍚" },
  { name: "Oats", emoji: "🌾" },
  { name: "Barley", emoji: "🌾" },
  { name: "Rye", emoji: "🌾" },
  { name: "Quinoa", emoji: "🌾" }, // Grain for quinoa
  { name: "Millet", emoji: "🌾" },
  // Spices (from plants)
  { name: "Chilli Pepper", emoji: "🌶️" },
  { name: "Turmeric Plant", emoji: "🌿" },
  { name: "Ginger Plant", emoji: "🌿" },
  { name: "Cinnamon Tree", emoji: "🌳" },
  { name: "Cardamom Plant", emoji: "🌿" },
  { name: "Clove Tree", emoji: "🌳" },
  { name: "Nutmeg Tree", emoji: "🌳" },
  // Trees
  { name: "Oak Tree", emoji: "🌳" },
  { name: "Pine Tree", emoji: "🌲" },
  { name: "Maple Tree", emoji: "🍁" },
  { name: "Palm Tree", emoji: "🌴" },
  { name: "Neem Tree", emoji: "🌳" },
  { name: "Eucalyptus Tree", emoji: "🌳" },
  { name: "Willow Tree", emoji: "🌳" },
  { name: "Birch Tree", emoji: "🌳" },
  // Legumes
  { name: "Beans (General)", emoji: "🫘" },
  { name: "Lentils", emoji: "🌿" }, // Plant that produces lentils
  { name: "Peas", emoji: "🫛" },
  { name: "Chickpeas", emoji: "🌿" }, // Plant that produces chickpeas
  { name: "Soybean", emoji: "🌿" },
  // Berries
  { name: "Blueberry", emoji: "🫐" },
  { name: "Raspberry", emoji: "🍓" }, // Using strawberry as stand-in
  { name: "Blackberry", emoji: "🫐" }, // Using blueberry as stand-in
  { name: "Cranberry", emoji: "🍓" },
  // Other Unique/Industrial
  { name: "Coffee Plant", emoji: "☕" },
  { name: "Tea Plant (Camellia sinensis)", emoji: "🫖" },
  { name: "Cotton Plant", emoji: "⚪" },
  { name: "Sugarcane", emoji: "🌿" },
  { name: "Bamboo", emoji: "🎍" },
  { name: "Hops", emoji: "🌿" }, // For beer
  { name: "Agave", emoji: "🌵" }, // For tequila, also ornamental
  { name: "Venus Flytrap", emoji: "🪴" }, // Carnivorous
  { name: "Pitcher Plant", emoji: "🪴" }, // Carnivorous
  { name: "Air Plant (Tillandsia)", emoji: "💨" } // Air + plant emoji
];

export const MONTHS: string[] = [
  "January", "February", "March", "April", "May", "June", 
  "July", "August", "September", "October", "November", "December"
];

// Kannada translations for months
export const MONTH_NAMES_KANNADA: Record<string, string> = {
  "January": "ಜನವರಿ",
  "February": "ಫೆಬ್ರವರಿ",
  "March": "ಮಾರ್ಚ್",
  "April": "ಏಪ್ರಿಲ್",
  "May": "ಮೇ",
  "June": "ಜೂನ್",
  "July": "ಜುಲೈ",
  "August": "ಆಗಸ್ಟ್",
  "September": "ಸೆಪ್ಟೆಂಬರ್",
  "October": "ಅಕ್ಟೋಬರ್",
  "November": "ನವೆಂಬರ್",
  "December": "ಡಿಸೆಂಬರ್"
};

export const GEMINI_TEXT_MODEL = "gemini-2.5-flash";
// For tasks involving image input, the same model supports multimodal inputs.
export const GEMINI_VISION_MODEL = "gemini-2.5-flash";

export const OPENWEATHERMAP_API_URL = "https://api.openweathermap.org/data/2.5/weather";

// --- BEGIN MASSIVE PLANT LIST FOR PLANT SCAN PAGE ---
// This list is for the PlantScanPage picker UI. Each entry has a name, emoji, and category.
export const PLANT_LIST: { name: string; emoji: string; category: string; nameKannada?: string }[] = [
  // Fruits
  // Fruits
  { name: "Coconut", emoji: "🥥", category: "Fruits", nameKannada: "ತೆಂಗಿನಕಾಯಿ" },
  { name: "Tamarind", emoji: "🍈", category: "Fruits", nameKannada: "ಹುಣಸೆ" },
  { name: "Apple", emoji: "🍎", category: "Fruits", nameKannada: "ಸೇಬು" },
  { name: "Banana", emoji: "🍌", category: "Fruits", nameKannada: "ಬಾಳೆ" },
  { name: "Mango", emoji: "🥭", category: "Fruits", nameKannada: "ಮಾವು" },
  { name: "Orange", emoji: "🍊", category: "Fruits", nameKannada: "ಕಿತ್ತಳೆ" },
  { name: "Papaya", emoji: "🥭", category: "Fruits", nameKannada: "ಪಪ್ಪಾಯ" },
  { name: "Guava", emoji: "🍈", category: "Fruits", nameKannada: "ಪೇರಲ" },
  { name: "Pineapple", emoji: "🍍", category: "Fruits", nameKannada: "ಅನಾನಸ್" },
  { name: "Watermelon", emoji: "🍉", category: "Fruits", nameKannada: "ಕಲ್ಲಂಗಡಿ" },
  { name: "Pomegranate", emoji: "🔴", category: "Fruits", nameKannada: "ದಾಳಿಂಬೆ" },
  { name: "Lychee", emoji: "🍈", category: "Fruits", nameKannada: "ಲಿಚಿ" },
  { name: "Jackfruit", emoji: "🍈", category: "Fruits", nameKannada: "ಹಲಸು" },
  { name: "Dragon Fruit", emoji: "🐉", category: "Fruits", nameKannada: "ಡ್ರಾಗನ್ ಫ್ರೂಟ್" },
  { name: "Passion Fruit", emoji: "🍈", category: "Fruits", nameKannada: "ಪ್ಯಾಶನ್ ಫ್ರೂಟ್" },
  { name: "Mulberry", emoji: "🫐", category: "Fruits", nameKannada: "ಹಿಪ್ಪಲಿ" },
  { name: "Blackberry", emoji: "🫐", category: "Fruits", nameKannada: "ಕಪ್ಪು ಬೆರ್ರಿ" },
  { name: "Blueberry", emoji: "🫐", category: "Fruits", nameKannada: "ನೀಲಿ ಬೆರ್ರಿ" },
  { name: "Raspberry", emoji: "🍓", category: "Fruits", nameKannada: "ರಾಸ್ಪ್ಬೆರಿ" },
  { name: "Cranberry", emoji: "🍓", category: "Fruits", nameKannada: "ಕ್ರಾನ್ಬೆರಿ" },
   { name: "Fig (1)", emoji: "🟣", category: "Fruits", nameKannada: "ಅಂಜೂರ" },
{ name: "Persimmon", emoji: "🟠", category: "Fruits", nameKannada: "ಪರ್ಸಿಮನ್" },
{ name: "Sapodilla", emoji: "🥔", category: "Fruits", nameKannada: "ಸಪೋಟ" },
{ name: "Starfruit (1)", emoji: "⭐", category: "Fruits", nameKannada: "ನಕ್ಷತ್ರ ಹಣ್ಣು" },
{ name: "Custard Apple (1)", emoji: "💚", category: "Fruits", nameKannada: "ಸೀತಾಫಲ" },
{ name: "Fig (2)", emoji: "🍈", category: "Fruits", nameKannada: "ಅಂಜೂರ" },
{ name: "Starfruit (2)", emoji: "🌟", category: "Fruits", nameKannada: "ನಕ್ಷತ್ರ ಹಣ್ಣು" },
{ name: "Custard Apple (2)", emoji: "🍏", category: "Fruits", nameKannada: "ಸೀತಾಫಲ" },
{ name: "Sapota (Chikoo)", emoji: "🥔", category: "Fruits", nameKannada: "ಸಪೋಟ" },
{ name: "Jamun", emoji: "🫐", category: "Fruits", nameKannada: "ನೇರಳೆ" },
{ name: "Ber (Indian Jujube)", emoji: "🍒", category: "Fruits", nameKannada: "ಬೋರೆ" },
{ name: "Ambarella", emoji: "🍏", category: "Fruits", nameKannada: "ಅಂಬರೆಲ್ಲಾ" },
{ name: "Wood Apple", emoji: "🥥", category: "Fruits", nameKannada: "ಬೇಲದ ಹಣ್ಣು" },
{ name: "Loquat", emoji: "🍑", category: "Fruits", nameKannada: "ಲೋಕ್ವಾಟ್" },
{ name: "Langsat", emoji: "🍋", category: "Fruits", nameKannada: "ಲ್ಯಾಂಗ್‌ಸ್ಯಾಟ್" },
{ name: "Rambutan", emoji: "🎯", category: "Fruits", nameKannada: "ರಾಂಬುಟಾನ್" },
{ name: "Mangosteen", emoji: "🟣", category: "Fruits", nameKannada: "ಮ್ಯಾಂಗೋಸ್ಟೀನ್" },
{ name: "Salak (Snake Fruit)", emoji: "🍎", category: "Fruits", nameKannada: "ಸಲಾಕ್" },
{ name: "Miracle Fruit", emoji: "🔮", category: "Fruits", nameKannada: "ಮಿರಾಕಲ್ ಫ್ರೂಟ್" },
{ name: "Cloudberry", emoji: "🟠", category: "Fruits", nameKannada: "ಕ್ಲೌಡ್ಬೆರಿ" },
{ name: "Hawthorn Berry", emoji: "🍒", category: "Fruits", nameKannada: "ಹಾಥಾರ್ನ್ ಬೆರಿ" },
  // Vegetables
  { name: "Tomato", emoji: "🍅", category: "Vegetables", nameKannada: "ಟೊಮೇಟೊ" },
  { name: "Potato", emoji: "🥔", category: "Vegetables", nameKannada: "ಆಲೂಗಡ್ಡೆ" },
  { name: "Carrot", emoji: "🥕", category: "Vegetables", nameKannada: "ಕ್ಯಾರೆಟ್" },
  { name: "Broccoli", emoji: "🥦", category: "Vegetables", nameKannada: "ಬ್ರೊಕೊಲಿ" },
  { name: "Spinach", emoji: "🥬", category: "Vegetables", nameKannada: "ಪಾಲಕ್" },
  { name: "Onion", emoji: "🧅", category: "Vegetables", nameKannada: "ಈರುಳ್ಳಿ" },
  { name: "Garlic", emoji: "🧄", category: "Vegetables", nameKannada: "ಬೆಳ್ಳುಳ್ಳಿ" },
  { name: "Eggplant", emoji: "🍆", category: "Vegetables", nameKannada: "ಬದನೇಕಾಯಿ" },
  { name: "Cucumber", emoji: "🥒", category: "Vegetables", nameKannada: "ಸೌತೆಕಾಯಿ" },
  { name: "Bell Pepper", emoji: "🌶", category: "Vegetables", nameKannada: "ಬೆಲ್ ಪೆಪ್ಪರ್" },
  { name: "Lettuce", emoji: "🥬", category: "Vegetables", nameKannada: "ಲೆಟ್ಯೂಸ್" },
  { name: "Pumpkin", emoji: "🎃", category: "Vegetables", nameKannada: "ಕುಂಬಳಕಾಯಿ" },
  { name: "Zucchini", emoji: "🥒", category: "Vegetables", nameKannada: "ಜುಕಿನಿ" },
  { name: "Cauliflower", emoji: "🥦", category: "Vegetables", nameKannada: "ಹೂಕೋಸು" },
  { name: "Radish", emoji: "🥕", category: "Vegetables", nameKannada: "ಮೂಲಂಗಿ" },
  { name: "Sweet Potato", emoji: "🍠", category: "Vegetables", nameKannada: "ಸಿಹಿ ಆಲೂಗಡ್ಡೆ" },
  { name: "Asparagus", emoji: "🥬", category: "Vegetables", nameKannada: "ಅಸ್ಪರಾಗಸ್" },
  { name: "Celery", emoji: "🥬", category: "Vegetables", nameKannada: "ಸೆಲರಿ" },
  { name: "Mushroom", emoji: "🍄", category: "Vegetables", nameKannada: "ಅಣಬೆ" },
  { name: "Corn (Maize)", emoji: "🌽", category: "Vegetables", nameKannada: "ಜೋಳ" },
  { name: "Turnip", emoji: "🫒", category: "Vegetables", nameKannada: "ಟರ್ನಿಪ್" },
{ name: "Beetroot", emoji: "🟥", category: "Vegetables", nameKannada: "ಬೀಟ್ರೂಟ್" },
{ name: "Taro Root", emoji: "🪵", category: "Vegetables", nameKannada: "ಕೇಸುವು" },
{ name: "Bottle Gourd", emoji: "🧪", category: "Vegetables", nameKannada: "ಸೋರೆಕಾಯಿ" },
{ name: "Drumstick", emoji: "🥢", category: "Vegetables", nameKannada: "ನುಗ್ಗೆಕಾಯಿ" },
{ name: "Brinjal", emoji: "🍆", category: "Vegetables", nameKannada: "ಬದನೇಕಾಯಿ" },
{ name: "Turnip", emoji: "🥕", category: "Vegetables", nameKannada: "ಟರ್ನಿಪ್" },
{ name: "Bottle Gourd", emoji: "🥒", category: "Vegetables", nameKannada: "ಸೋರೆಕಾಯಿ" },
{ name: "Bitter Gourd", emoji: "🥒", category: "Vegetables", nameKannada: "ಹಾಗಲಕಾಯಿ" },
{ name: "Snake Gourd", emoji: "🥒", category: "Vegetables", nameKannada: "ಪಡವಲಕಾಯಿ" },
{ name: "Drumstick", emoji: "🥬", category: "Vegetables", nameKannada: "ನುಗ್ಗೆಕಾಯಿ" },
{ name: "Yam", emoji: "🍠", category: "Vegetables", nameKannada: "ಸೂರಣ" },
{ name: "Cluster Beans", emoji: "🌿", category: "Vegetables", nameKannada: "ಗೋರುಚಿಕ್ಕುಡು" },
{ name: "French Beans", emoji: "🌱", category: "Vegetables", nameKannada: "ಫ್ರೆಂಚ್ ಬೀನ್ಸ್" },
{ name: "Kohlrabi", emoji: "🥦", category: "Vegetables", nameKannada: "ಕೋಲ್ರಾಬಿ" },
{ name: "Taro Root", emoji: "🍠", category: "Vegetables", nameKannada: "ಕೇಸುವು" },
{ name: "Celeriac", emoji: "🥬", category: "Vegetables", nameKannada: "ಸೆಲೆರಿಯಾಕ್" },
{ name: "Fiddlehead Fern", emoji: "🌿", category: "Vegetables", nameKannada: "ಫಿಡಲ್‌ಹೆಡ್ ಫರ್ನ್" },
{ name: "Nopal (Cactus Pad)", emoji: "🌵", category: "Vegetables", nameKannada: "ನೋಪಾಲ್" },
{ name: "Romanesco", emoji: "🥦", category: "Vegetables", nameKannada: "ರೊಮನೆಸ್ಕೊ" },
{ name: "Daikon Radish", emoji: "🥕", category: "Vegetables", nameKannada: "ದೈಕಾನ್ ಮೂಲಂಗಿ" },
{ name: "Seaweed", emoji: "🟢", category: "Vegetables", nameKannada: "ಸಮುದ್ರ ಹುಲ್ಲು" },
  // Pulses
  { name: "Pigeon Pea", emoji: "🫘", category: "Pulses", nameKannada: "ತೊಗರಿ" },
  { name: "Black Gram", emoji: "🫘", category: "Pulses", nameKannada: "ಉದ್ದು" },
  { name: "Green Gram", emoji: "🫘", category: "Pulses", nameKannada: "ಹೆಸರುಕಾಳು" },
  { name: "Chickpea", emoji: "🫘", category: "Pulses", nameKannada: "ಕಡಲೆ" },
  { name: "Lentil", emoji: "🫘", category: "Pulses", nameKannada: "ಮಸೂರ" },
  { name: "Kidney Bean", emoji: "🫘", category: "Pulses", nameKannada: "ರಾಜ್ ಮಾ" },
  { name: "Soybean", emoji: "🫘", category: "Pulses", nameKannada: "ಸೋಯಾಬೀನ್" },
  { name: "Moth Bean", emoji: "🫘", category: "Pulses", nameKannada: "ಮಾಟ್ ಬೀನ್" },
  { name: "Horse Gram", emoji: "🫘", category: "Pulses", nameKannada: "ಹುರುಳಿ" },
  { name: "Field Pea", emoji: "🫘", category: "Pulses", nameKannada: "ಬಟಾಣಿ" },
  { name: "Red Lentil", emoji: "🔴", category: "Pulses", nameKannada: "ಕೆಂಪು ಮಸೂರ" },
  { name: "White Pea", emoji: "⚪", category: "Pulses", nameKannada: "ಬಿಳಿ ಬಟಾಣಿ" },
{ name: "Adzuki Bean", emoji: "🔵", category: "Pulses", nameKannada: "ಅಡ್ಜುಕಿ ಬೀನ್" },
{ name: "Bambara Groundnut", emoji: "🟤", category: "Pulses", nameKannada: "ಬಂಬಾರಾ ಕಡಲೆ" },
{ name: "Cowpea", emoji: "🟠", category: "Pulses", nameKannada: "ಅಲಸಂದೆ" },
  // Cereals & Millets
  { name: "Rice", emoji: "🍚", category: "Cereals & Millets", nameKannada: "ಅಕ್ಕಿ" },
  { name: "Wheat", emoji: "🌾", category: "Cereals & Millets", nameKannada: "ಗೋಧಿ" },
  { name: "Barley", emoji: "🌾", category: "Cereals & Millets", nameKannada: "ಬಾರ್ಲಿ" },
  { name: "Oats", emoji: "🌾", category: "Cereals & Millets", nameKannada: "ಓಟ್ಸ್" },
  { name: "Rye", emoji: "🌾", category: "Cereals & Millets", nameKannada: "ರೈ" },
  { name: "Quinoa", emoji: "🌾", category: "Cereals & Millets", nameKannada: "ಕ್ವಿನೋವಾ" },
  { name: "Millet", emoji: "🌾", category: "Cereals & Millets", nameKannada: "ಸಿರಿಧಾನ್ಯ" },
  { name: "Sorghum", emoji: "🌾", category: "Cereals & Millets", nameKannada: "ಜೋಳ" },
  { name: "Maize", emoji: "🌽", category: "Cereals & Millets", nameKannada: "ಮೆಕ್ಕೆಜೋಳ" },
  { name: "Foxtail Millet", emoji: "🌾", category: "Cereals & Millets", nameKannada: "ನವಣೆ" },
  { name: "Little Millet", emoji: "🟡", category: "Cereals & Millets", nameKannada: "ಸಾವೆ" },
{ name: "Kodo Millet", emoji: "🟤", category: "Cereals & Millets", nameKannada: "ಹಾರಕ" },
{ name: "Barnyard Millet", emoji: "⚪", category: "Cereals & Millets", nameKannada: "ಊದಲು" },
{ name: "Teff", emoji: "🟫", category: "Cereals & Millets", nameKannada: "ಟೆಫ್" },
{ name: "Amaranth", emoji: "🔆", category: "Cereals & Millets", nameKannada: "ದಂಟು" },
{ name: "Little Millet", emoji: "🌾", category: "Cereals & Millets", nameKannada: "ಸಾವೆ" },
{ name: "Kodo Millet", emoji: "🌾", category: "Cereals & Millets", nameKannada: "ಹಾರಕ" },
{ name: "Barnyard Millet", emoji: "🌾", category: "Cereals & Millets", nameKannada: "ಊದಲು" },
{ name: "Proso Millet", emoji: "🌾", category: "Cereals & Millets", nameKannada: "ಬಾರಿಗೆ" },
{ name: "Pearl Millet (Bajra)", emoji: "🌾", category: "Cereals & Millets", nameKannada: "ಸಜ್ಜೆ" },
{ name: "Finger Millet (Ragi)", emoji: "🌾", category: "Cereals & Millets", nameKannada: "ರಾಗಿ" },
{ name: "Teff", emoji: "🌾", category: "Cereals & Millets", nameKannada: "ಟೆಫ್" },
{ name: "Freekeh", emoji: "🌾", category: "Cereals & Millets", nameKannada: "ಫ್ರೀಕೆಹ್" },
{ name: "Fonio", emoji: "🌾", category: "Cereals & Millets", nameKannada: "ಫೊನಿಯೊ" },
{ name: "Amaranth", emoji: "🌾", category: "Cereals & Millets", nameKannada: "ದಂಟು" },
{ name: "Spelt", emoji: "🌾", category: "Cereals & Millets", nameKannada: "ಸ್ಪೆಲ್ಟ್" },
{ name: "Einkorn", emoji: "🌾", category: "Cereals & Millets", nameKannada: "ಐನ್‌ಕಾರ್ನ್" },
  // Spices
  { name: "Chilli Pepper", emoji: "🌶", category: "Spices", nameKannada: "ಮೆಣಸಿನಕಾಯಿ" },
  { name: "Turmeric", emoji: "🌿", category: "Spices", nameKannada: "ಅರಿಶಿನ" },
  { name: "Ginger", emoji: "🌿", category: "Spices", nameKannada: "ಶುಂಠಿ" },
  { name: "Cinnamon", emoji: "🌳", category: "Spices", nameKannada: "ದಾಲ್ಚಿನ್ನಿ" },
  { name: "Cardamom", emoji: "🌿", category: "Spices", nameKannada: "ಏಲಕ್ಕಿ" },
  { name: "Clove", emoji: "🌳", category: "Spices", nameKannada: "ಲವಂಗ" },
  { name: "Nutmeg", emoji: "🌳", category: "Spices", nameKannada: "ಜಾಯಿಕಾಯಿ" },
  { name: "Black Pepper", emoji: "⚫", category: "Spices", nameKannada: "ಕರಿಮೆಣಸು" },
  { name: "Mustard", emoji: "🌱", category: "Spices", nameKannada: "ಸಾಸಿವೆ" },
  { name: "Fenugreek", emoji: "🌱", category: "Spices", nameKannada: "ಮೆಂತೆ" },
  { name: "Star Anise", emoji: "✨", category: "Spices", nameKannada: "ಚಕ್ರ ಫೂಲ" },
{ name: "Bay Leaf", emoji: "🍂", category: "Spices", nameKannada: "ತಮಾಲಪತ್ರೆ" },
{ name: "Saffron", emoji: "🧡", category: "Spices", nameKannada: "ಕೇಸರಿ" },
{ name: "Fennel", emoji: "🌾", category: "Spices", nameKannada: "ಸೋಂಪು" },
{ name: "Coriander", emoji: "🍃", category: "Spices", nameKannada: "ಕೊತ್ತಂಬರಿ" },
{ name: "Saffron", emoji: "🧡", category: "Spices", nameKannada: "ಕೇಸರಿ" },
{ name: "Bay Leaf", emoji: "🍃", category: "Spices", nameKannada: "ತಮಾಲಪತ್ರೆ" },
{ name: "Coriander", emoji: "🌿", category: "Spices", nameKannada: "ಕೊತ್ತಂಬರಿ" },
{ name: "Fennel", emoji: "🌿", category: "Spices", nameKannada: "ಸೋಂಪು" },
{ name: "Cumin", emoji: "⚫", category: "Spices", nameKannada: "ಜೀರಿಗೆ" },
{ name: "Tamarind Seed", emoji: "🌰", category: "Spices", nameKannada: "ಹುಣಸೆ ಬೀಜ" },
{ name: "Ajwain (Carom Seed)", emoji: "🌱", category: "Spices", nameKannada: "ಓಮ" },
{ name: "Mace", emoji: "🧡", category: "Spices", nameKannada: "ಜಾವಿತ್ರಿ" },
{ name: "Fenugreek", emoji: "🟤", category: "Spices", nameKannada: "ಮೆಂತೆ" },
{ name: "Anise", emoji: "🌿", category: "Spices", nameKannada: "ಅನಸಾದ" },
{ name: "Nigella Seed (Kalonji)", emoji: "⚫", category: "Spices", nameKannada: "ಕರಿಂಜೀರಿಗೆ" },
{ name: "Sumac", emoji: "🔴", category: "Spices", nameKannada: "ಸುಮಾಕ್" },
{ name: "Wasabi", emoji: "🟢", category: "Spices", nameKannada: "ವಸಾಬಿ" },

  // Commercial Crops
  { name: "Cotton", emoji: "⚪", category: "Commercial Crops", nameKannada: "ಹತ್ತಿ" },
  { name: "Sugarcane", emoji: "🌿", category: "Commercial Crops", nameKannada: "ಕಬ್ಬು" },
  { name: "Tea", emoji: "🫖", category: "Commercial Crops", nameKannada: "ಚಹಾ" },
  { name: "Coffee", emoji: "☕", category: "Commercial Crops", nameKannada: "ಕಾಫಿ" },
  { name: "Tobacco", emoji: "🌿", category: "Commercial Crops", nameKannada: "ತಂಬಾಕು" },
  { name: "Jute", emoji: "🌿", category: "Commercial Crops", nameKannada: "ಸಣಬು" },
  { name: "Rubber", emoji: "🌳", category: "Commercial Crops", nameKannada: "ರಬ್ಬರ್" },
  { name: "Oil Palm", emoji: "🌴", category: "Commercial Crops", nameKannada: "ತೈಲ ತೆಂಗು" },
  { name: "Groundnut", emoji: "🥜", category: "Commercial Crops", nameKannada: "ಕಡಲೆಕಾಯಿ" },
  { name: "Sunflower (Oilseed)", emoji: "🌻", category: "Commercial Crops", nameKannada: "ಸೂರ್ಯಕಾಂತಿ" },
  { name: "Hemp", emoji: "🌿", category: "Commercial Crops", nameKannada: "ಸಣಬು" },
{ name: "Areca Nut", emoji: "🥥", category: "Commercial Crops", nameKannada: "ಅಡಿಕೆ" },
{ name: "Cocoa", emoji: "🍫", category: "Commercial Crops", nameKannada: "ಕೋಕೋ" },
{ name: "Sisal", emoji: "🧵", category: "Commercial Crops", nameKannada: "ಸಿಸಲ್" },
{ name: "Castor", emoji: "🧪", category: "Commercial Crops", nameKannada: "ಹರಳು" },
  // Ornamental Plants
  { name: "Rose", emoji: "🌹", category: "Ornamental Plants", nameKannada: "ಗುಲಾಬಿ" },
  { name: "Sunflower", emoji: "🌻", category: "Ornamental Plants", nameKannada: "ಸೂರ್ಯಕಾಂತಿ" },
  { name: "Tulip", emoji: "🌷", category: "Ornamental Plants", nameKannada: "ಟುಲಿಪ್" },
  { name: "Lily", emoji: "🌸", category: "Ornamental Plants", nameKannada: "ಲಿಲಿ" },
  { name: "Orchid", emoji: "🌺", category: "Ornamental Plants", nameKannada: "ಆರ್ಕಿಡ್" },
  { name: "Fern", emoji: "🌿", category: "Ornamental Plants", nameKannada: "ಜರಿಗಿಡ" },
  { name: "Bonsai", emoji: "🌳", category: "Ornamental Plants", nameKannada: "ಬೋನ್ಸಾಯಿ" },
  { name: "Cactus", emoji: "🌵", category: "Ornamental Plants", nameKannada: "ಕಳ್ಳಿ" },
  { name: "Lavender", emoji: "💐", category: "Ornamental Plants", nameKannada: "ಲ್ಯಾವೆಂಡರ್" },
  { name: "Marigold", emoji: "🌼", category: "Ornamental Plants", nameKannada: "ಚೆಂಡುಹೂವು" },
  { name: "Peony", emoji: "🌺", category: "Ornamental Plants", nameKannada: "ಪಿಯೊನಿ" },
{ name: "Zinnia", emoji: "🌼", category: "Ornamental Plants", nameKannada: "ಜಿನ್ನಿಯಾ" },
{ name: "Chrysanthemum", emoji: "💮", category: "Ornamental Plants", nameKannada: "ಸೇವಂತಿಗೆ" },
{ name: "Begonia", emoji: "🌸", category: "Ornamental Plants", nameKannada: "ಬೆಗೋನಿಯಾ" },
{ name: "Petunia", emoji: "🌺", category: "Ornamental Plants", nameKannada: "ಪೆಟುನಿಯಾ" },
{ name: "Zinnia", emoji: "🌼", category: "Ornamental Plants", nameKannada: "ಜಿನ್ನಿಯಾ" },
{ name: "Petunia", emoji: "🌺", category: "Ornamental Plants", nameKannada: "ಪೆಟುನಿಯಾ" },
{ name: "Hibiscus", emoji: "🌺", category: "Ornamental Plants", nameKannada: "ದಾಸವಾಳ" },
{ name: "Begonia", emoji: "🌸", category: "Ornamental Plants", nameKannada: "ಬೆಗೋನಿಯಾ" },
{ name: "Ixora", emoji: "🌸", category: "Ornamental Plants", nameKannada: "ಕೊರಳಹೂವು" },
{ name: "Lantana", emoji: "🌸", category: "Ornamental Plants", nameKannada: "ಲಂಟಾನಾ" },
{ name: "Portulaca", emoji: "🌼", category: "Ornamental Plants", nameKannada: "ಪೋರ್ಟುಲಾಕಾ" },
{ name: "Coleus", emoji: "🍃", category: "Ornamental Plants", nameKannada: "ಕೋಲಿಯಸ್" },
{ name: "Bougainvillea", emoji: "🌺", category: "Ornamental Plants", nameKannada: "ಬೋಗನವಿಲ್ಲ" },
{ name: "Delphinium", emoji: "💙", category: "Ornamental Plants", nameKannada: "ಡೆಲ್ಫಿನಿಯಮ್" },
{ name: "Maranta (Prayer Plant)", emoji: "🪴", category: "Ornamental Plants", nameKannada: "ಮರಾಂಟಾ" },

  // Medicinal Plants
  { name: "Neem", emoji: "🌳", category: "Medicinal Plants", nameKannada: "ಬೇವು" },
  { name: "Tulsi (Holy Basil)", emoji: "🌿", category: "Medicinal Plants", nameKannada: "ತುಳಸಿ" },
  { name: "Aloe Vera", emoji: "🪴", category: "Medicinal Plants", nameKannada: "ಲೋಸರೆ" },
  { name: "Ashwagandha", emoji: "🌿", category: "Medicinal Plants", nameKannada: "ಅಶ್ವಗಂಧ" },
  { name: "Brahmi", emoji: "🌱", category: "Medicinal Plants", nameKannada: "ಬ್ರಾಹ್ಮಿ" },
  { name: "Gotu Kola", emoji: "🌱", category: "Medicinal Plants", nameKannada: "ಒಂಡೆಲಗ" },
  { name: "Shatavari", emoji: "🌱", category: "Medicinal Plants", nameKannada: "ಶತಾವರಿ" },
  { name: "Betel Leaf", emoji: "🍃", category: "Medicinal Plants", nameKannada: "ವೀಳದಲೆ" },
  { name: "Stevia", emoji: "🍃", category: "Medicinal Plants", nameKannada: "ಸ್ಟೀವಿಯಾ" },
  { name: "Moringa (Drumstick)", emoji: "🌿", category: "Medicinal Plants", nameKannada: "ನುಗ್ಗೆ" },
  { name: "Kalmegh", emoji: "🌱", category: "Medicinal Plants", nameKannada: "ಕಾಳಮೇಘ" },
{ name: "Giloy", emoji: "🍃", category: "Medicinal Plants", nameKannada: "ಅಮೃತಬಳ್ಳಿ" },
{ name: "Indian Senna", emoji: "🌿", category: "Medicinal Plants", nameKannada: "ನೇಲವಕೆ" },
{ name: "Bael", emoji: "🍐", category: "Medicinal Plants", nameKannada: "ಬಿಲ್ವ" },
{ name: "Indian Gooseberry", emoji: "🟢", category: "Medicinal Plants", nameKannada: "ನೆಲ್ಲಿಕಾಯಿ" },
{ name: "Arjuna Tree", emoji: "🌳", category: "Medicinal Plants", nameKannada: "ಅರ್ಜುನ" },
{ name: "Guggul", emoji: "🌿", category: "Medicinal Plants", nameKannada: "ಗುಗ್ಗುಳ" },
{ name: "Kalmegh", emoji: "🌱", category: "Medicinal Plants", nameKannada: "ಕಾಳಮೇಘ" },
{ name: "Giloy", emoji: "🌿", category: "Medicinal Plants", nameKannada: "ಅಮೃತಬಳ್ಳಿ" },
{ name: "Manjistha", emoji: "🌱", category: "Medicinal Plants", nameKannada: "ಮಂಜಿಷ್ಠ" },
{ name: "Indian Gooseberry (Amla)", emoji: "🍏", category: "Medicinal Plants", nameKannada: "ನೆಲ್ಲಿಕಾಯಿ" },
{ name: "Yarrow", emoji: "🌼", category: "Medicinal Plants", nameKannada: "ಯಾರೋ" },
{ name: "Lemongrass", emoji: "🌾", category: "Medicinal Plants", nameKannada: "ಲೆಮನ್ಗ್ರಾಸ್" },
{ name: "Licorice", emoji: "🌱", category: "Medicinal Plants", nameKannada: "ಯಷ್ಟಿಮಧು" },
{ name: "Gotu Kola", emoji: "🌿", category: "Medicinal Plants", nameKannada: "ಒಂಡೆಲಗ" },
{ name: "Brahmi", emoji: "🌿", category: "Medicinal Plants", nameKannada: "ಬ್ರಾಹ್ಮಿ" },
{ name: "Echinacea", emoji: "🌸", category: "Medicinal Plants", nameKannada: "ಎಕಿನೇಸಿಯಾ" },
  // Trees
  { name: "Baobab", emoji: "🌳", category: "Trees", nameKannada: "ಬಾವೊಬಾಬ್" },
  { name: "Sandalwood", emoji: "🌳", category: "Trees", nameKannada: "ಶ್ರೀಗಂಧ" },
  { name: "Mahogany", emoji: "🌳", category: "Trees", nameKannada: "ಮಹೋಗಾನಿ" },
  { name: "Teak", emoji: "🌳", category: "Trees", nameKannada: "ತೇಗು" },
  { name: "Bamboo", emoji: "🎍", category: "Trees", nameKannada: "ಬಿದಿರು" },
  { name: "Palm", emoji: "🌴", category: "Trees", nameKannada: "ತಾಳೆ" },
  { name: "Red Maple", emoji: "🍁", category: "Trees", nameKannada: "ಕೆಂಪು ಮ್ಯಾಪಲ್" },
  { name: "Cedar", emoji: "🌲", category: "Trees", nameKannada: "ಸೀಡರ್" },
  { name: "Spruce", emoji: "🌲", category: "Trees", nameKannada: "ಸ್ಪ್ರೂಸ್" },
  { name: "Fir", emoji: "🌲", category: "Trees", nameKannada: "ಫರ್" },
  { name: "Hemlock", emoji: "🌲", category: "Trees", nameKannada: "ಹೆಮ್ಲಾಕ್" },
  { name: "Larch", emoji: "🌲", category: "Trees", nameKannada: "ಲಾರ್ಚ್" },
  { name: "Tamarack", emoji: "🌲", category: "Trees", nameKannada: "ತಮಾರಾಕ್" },
  { name: "Douglas Fir", emoji: "🌲", category: "Trees", nameKannada: "ಡಗ್ಲಸ್ ಫರ್" },
  { name: "Redwood", emoji: "🌲", category: "Trees", nameKannada: "ರೆಡ್‌ವುಡ್" },
  { name: "Sequoia", emoji: "🌲", category: "Trees", nameKannada: "ಸೆಕ್ವೊಯಾ" },
  { name: "Ginkgo", emoji: "🌳", category: "Trees", nameKannada: "ಗಿಂಗ್ಕೋ" },
  { name: "Cycad", emoji: "🌴", category: "Trees", nameKannada: "ಸೈಕಾಡ್" },
  { name: "Sago Palm", emoji: "🌴", category: "Trees", nameKannada: "ಸಾಗೋ ತಾಳೆ" },
  { name: "Rattan", emoji: "🌴", category: "Trees", nameKannada: "ರತ್ತನ್" },
  // Herbs
  { name: "Basil", emoji: "🌿", category: "Herbs", nameKannada: "ತುಳಸಿ" },
  { name: "Mint", emoji: "🍃", category: "Herbs", nameKannada: "ಪುದೀನಾ" },
  { name: "Rosemary", emoji: "🌿", category: "Herbs", nameKannada: "ರೋಸ್ಮರಿ" },
  { name: "Thyme", emoji: "🌿", category: "Herbs", nameKannada: "ಥೈಮ್" },
  { name: "Cilantro (Coriander)", emoji: "🌿", category: "Herbs", nameKannada: "ಕೊತ್ತಂಬರಿ" },
  { name: "Parsley", emoji: "🌿", category: "Herbs", nameKannada: "ಪಾರ್ಸ್ಲಿ" },
  { name: "Dill", emoji: "🌿", category: "Herbs", nameKannada: "ಸಬ್ಬಸಿಗೆ" },
 { name: "Oregano", emoji: "🌿", category: "Herbs", nameKannada: "ಒರೆಗಾನೊ" },
  { name: "Sage", emoji: "🌿", category: "Herbs", nameKannada: "ಸೇಜ್" },
  { name: "Chamomile", emoji: "🌼", category: "Herbs", nameKannada: "ಚ್ಯಾಮೊಮೈಲ್" },
  
];
// --- END MASSIVE PLANT LIST ---

export const COMMON_CROPS = [
  "Rice", "Wheat", "Maize", "Tomato", "Potato", "Banana", "Sugarcane", "Cotton", "Groundnut", "Chilli", "Onion", "Millet", "Soybean", "Sunflower", "Mustard", "Pea", "Sorghum", "Barley", "Bajra", "Coconut", "Mango", "Apple", "Orange", "Grape", "Pomegranate", "Lemon", "Cabbage", "Cauliflower", "Carrot", "Beans", "Okra", "Pumpkin", "Papaya", "Guava", "Pineapple", "Watermelon", "Cucumber"
];

// Kannada translations for crops
export const CROP_NAMES_KANNADA: Record<string, string> = {
  "Rice": "ಅಕ್ಕಿ",
  "Wheat": "ಗೋಧಿ",
  "Maize": "ಜೋಳ",
  "Tomato": "ಟೊಮ್ಯಾಟೊ",
  "Potato": "ಆಲೂಗಡ್ಡೆ",
  "Banana": "ಬಾಳೆಹಣ್ಣು",
  "Sugarcane": "ಕಬ್ಬು",
  "Cotton": "ಹತ್ತಿ",
  "Groundnut": "ಶೇಂಗ",
  "Chilli": "ಮೆಣಸಿನಕಾಯಿ",
  "Onion": "ಈರುಳ್ಳಿ",
  "Millet": "ರಾಗಿ",
  "Soybean": "ಸೋಯಾಬೀನ್",
  "Sunflower": "ಸೂರ್ಯಕಾಂತಿ",
  "Mustard": "ಸಾಸಿವೆ",
  "Pea": "ಬಟಾಣಿ",
  "Sorghum": "ಜೋಳ",
  "Barley": "ಜವೆಗೋಧಿ",
  "Bajra": "ಸಜ್ಜೆ",
  "Coconut": "ತೆಂಗಿನಕಾಯಿ",
  "Mango": "ಮಾವು",
  "Apple": "ಸೇಬು",
  "Orange": "ಕಿತ್ತಳೆ",
  "Grape": "ದ್ರಾಕ್ಷಿ",
  "Pomegranate": "ದಾಳಿಂಬೆ",
  "Lemon": "ನಿಂಬೆಹಣ್ಣು",
  "Cabbage": "ಎಲೆಕೋಸು",
  "Cauliflower": "ಹೂಕೋಸು",
  "Carrot": "ಕ್ಯಾರೆಟ್",
  "Beans": "ಅವರೆಕಾಳು",
  "Okra": "ಬೆಂಡೆಕಾಯಿ",
  "Pumpkin": "ಕುಂಬಳಕಾಯಿ",
  "Papaya": "ಪಪ್ಪಾಯ",
  "Guava": "ಪೇರಲ",
  "Pineapple": "ಅನಾನಸ್",
  "Watermelon": "ಕಲ್ಲಂಗಡಿ",
  "Cucumber": "ಸೌತೆಕಾಯಿ"
};
